language: node_js
sudo: false
node_js:
- '4'
- '5'
- '6'
- '7'
- 'node'

install:
  - npm install
  - npm run build

script:
  - true
  # - npm run test

cache:
  directories:
    - node_modules

before_deploy:
  - openssl aes-256-cbc -K $encrypted_563d01e56a2d_key -iv $encrypted_563d01e56a2d_iv -in scripts/deploy_ed25519.enc -out /tmp/deploy_ed25519 -d
  - eval "$(ssh-agent -s)"
  - chmod 0600 /tmp/deploy_ed25519
  - ssh-add /tmp/deploy_ed25519

deploy:
  # deploy master to the staging/test environment
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh staging
    on:
      branch: master
      node: 'node'

  # deploy release to the production environment
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh production
    on:
      branch: release
      node: 'node'

addons:
  ssh_known_hosts: proposal.dash.org
